service:
    daemon_mode: True
    update_interval: 10
    self_discovery: False
    bind_to_ip: False

mqtt:
    host: mqtt
    port: 1883
    client_id: ac_to_mqtt
    user:
    passwd:
    topic_prefix: /aircon
    auto_discovery_topic: homeassistant
    auto_discovery_topic_retain: False
    discovery: False

devices:
  - ip:
    mac:
    name:
    port: